# Generated by Django 5.2.7 on 2025-11-03 14:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_patientprofile_age_patientprofile_blood_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="clinic_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="consultation_type",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("IN_PERSON", "In-Person"),
                    ("BOTH", "Both"),
                ],
                default="BOTH",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="medical_council",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="medical_degree_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.DoctorProfile.get_degree_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="medical_registration_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.DoctorProfile.get_reg_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="medical_registration_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.DoctorProfile.get_photo_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="qualification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
