# Generated by Django 5.2.7 on 2025-11-09 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_doctorpatientconnection"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientHealthMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("heart_rate_bpm", models.IntegerField(blank=True, null=True)),
                ("blood_pressure_systolic", models.IntegerField(blank=True, null=True)),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True),
                ),
                ("blood_count", models.FloatField(blank=True, null=True)),
                ("glucose_level_mg_dl", models.FloatField(blank=True, null=True)),
                ("sleep_hours", models.FloatField(blank=True, null=True)),
                ("steps_taken", models.IntegerField(blank=True, null=True)),
                ("mood", models.CharField(blank=True, max_length=50)),
                ("symptoms", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_metrics",
                        to="core.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
