# Generated by Django 5.2.7 on 2025-11-10 10:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_patienthealthmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.get_patient_photo_upload_path,
            ),
        ),
    ]
