# Generated by Django 5.2.7 on 2025-11-15 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_patientprofile_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BOOKED", "Booked"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[("ONLINE", "Online"), ("IN_PERSON", "In-Person")],
                        default="IN_PERSON",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("prescription", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "PATIENT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "unique_together": {("doctor", "start_time")},
            },
        ),
    ]
