# Generated by Django 5.2.7 on 2025-11-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_message_file_alter_message_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="emergency_contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="hospital_reception_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
