# Generated by Django 5.2.7 on 2025-11-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_doctorprofile_emergency_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="chat_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("BUSY", "Busy"),
                    ("OFFLINE", "Not Accepting Chats"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="work_hour_end",
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="work_hour_start",
            field=models.IntegerField(default=9),
        ),
    ]
