# Generated by Django 5.2.7 on 2025-11-22 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_doctorprofile_chat_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalreport",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"user_type": "DOCTOR"},
                related_name="shared_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_by",
            field=models.ManyToManyField(
                blank=True, related_name="deleted_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
